[project]
name = "mcp-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arxiv>=2.2.0",
    "fastmcp>=2.5.1",
    "mcp>=1.9.1",
    "nest-asyncio>=1.6.0",
    "openai>=1.82.0",
]
